### ISSUE TITLE
Offener Accesspoint

### ISSUE THREAD

**Issue by Dickimo** [DIYDave/Scroll-Box-Verion-2#1]
Hallo, 

erstmal herzlichen Dank für dieses tolle Projekt. Habe es heute mal getestet. Es funktioniert soweit, jedoch wird, obwohl der ESP im Netzwerk angemeldet ist, ein offener Accesspoint Namens "ESP-0D4..." erzeugt. 
Ist da irgendwo ein Fehler? 

Edit: ist es möglich ein OLED Display mit I2C zu benutzen? Habe noch einige hier liegen ;-)

**Comment by DIYDave** [comment]
Hallo Markus
Danke für Dein Lob!
Der ESP ist entweder AP, dann hat er die SSID "Scrollbox" 
Oder, nach erfolgreicher WLAN Konfiguration, ist er Client und sollte nicht mehr als AP erscheinen.
Deine Beobachtung sagt mir daher leider nichts.

Das Display könnte auch über I2C angesteuert werden. Ich habe das getrennt weil die Matrix schon an I2C hängt.
Ich würde mir den Aufwand sparen alles umzustellen und ein SPI-Teil kaufen.
Danke und Gruss, Dave

**Comment by Dickimo** [comment]
Hallo Dave, 

danke für die schnelle und freundliche Antwort.

Das mit dem AP muss ich noch mal checken, werde nochmal den ESP neu flashen.

Von den I2C-Displays habe ich noch einige liegen, von daher werde ich mal schauen wie ich das umsetze. 
Läuft auch ohne Display, ist im Moment nur als Test gelaufen. Mein Anwendungsfall ist leider nicht mehr gegeben, aber ich werde schon eine andere "Spielerei" finden.

Mit freundlichem Gruß
Markus
